name: CI-extensions-list

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@dynamic-docker

      - name: PHPUnit Tests
        uses: php-actions/phpunit@dynamic-docker
        with:
          php_extensions:
            - bcmath
            - gd
            - intl
            - pdo_mysql
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
