name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: PHPUnit Tests
        uses: php-actions/phpunit@17-php-versions
        with:
          php_version: "8.0"
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
